import type { NextPage } from 'next'
import Head from 'next/head'
import { Explanation } from '../components/Explanation'
import { FinalCTA } from '../components/FinalCTA'
import { Footer } from '../components/Footer'
import { Header } from '../components/Header'
import { Hero } from '../components/Hero'
import { Motivation } from '../components/Motivation'

const Home: NextPage = () => {
  // const { data } = trpc.useQuery(['example.hello', { text: 'from tRPC' }])

  return (
    <>
      <Head>
        <title>Transmídia Storytelling</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Hero />
        <Explanation />
        <Motivation />
        <FinalCTA />
      </main>
      <Footer />
    </>
  )
}

export default Home
